version: '3'

services:
  backend:
    image: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "3001:3001"

  frontend:
    image: frontend
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:3000" # Adjust this to your frontend's port

